version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50005:50005"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped

  frontend:
    build:
      context: ../aigs-react-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge